// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCzB1gu59ebkx01SIbyoyc2-4tYwFdqmIE',
    appId: '1:960170418592:web:7c45f162f18815347984c5',
    messagingSenderId: '960170418592',
    projectId: 'concessiontracker',
    authDomain: 'concessiontracker.firebaseapp.com',
    storageBucket: 'concessiontracker.firebasestorage.app',
    measurementId: 'G-NPMDMBSDH1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBwbGEh6fhSvgnoJN--FaGP2FkBWW7zdrg',
    appId: '1:960170418592:android:b6d65b9b2c9a49cf7984c5',
    messagingSenderId: '960170418592',
    projectId: 'concessiontracker',
    storageBucket: 'concessiontracker.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDniJjYdXf7uaWlAXgb07EL_3CB3lK8O-c',
    appId: '1:960170418592:ios:7a1049e9b7193e517984c5',
    messagingSenderId: '960170418592',
    projectId: 'concessiontracker',
    storageBucket: 'concessiontracker.firebasestorage.app',
    iosBundleId: 'com.example.concessionTracker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDniJjYdXf7uaWlAXgb07EL_3CB3lK8O-c',
    appId: '1:960170418592:ios:7a1049e9b7193e517984c5',
    messagingSenderId: '960170418592',
    projectId: 'concessiontracker',
    storageBucket: 'concessiontracker.firebasestorage.app',
    iosBundleId: 'com.example.concessionTracker',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCzB1gu59ebkx01SIbyoyc2-4tYwFdqmIE',
    appId: '1:960170418592:web:870b4f31af72342c7984c5',
    messagingSenderId: '960170418592',
    projectId: 'concessiontracker',
    authDomain: 'concessiontracker.firebaseapp.com',
    storageBucket: 'concessiontracker.firebasestorage.app',
    measurementId: 'G-TJDJTRJ6RP',
  );
}
